# Generated by Django 3.0.7 on 2020-07-31 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('app', '0001_initial'),
        ('userexpert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relationexpertapplication',
            name='expert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rel_exp_app', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт'),
        ),
        migrations.AddField(
            model_name='direction',
            name='commission',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('admin_group', False), ('common_commission', False)), on_delete=django.db.models.deletion.CASCADE, to='userexpert.CustomGroup', verbose_name='Экспертная комиссия'),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='application',
            name='vuz',
            field=models.ForeignKey(default=None, limit_choices_to={'is_vuz': True}, on_delete=django.db.models.deletion.CASCADE, to='info.Company', verbose_name='ВУЗ'),
        ),
        migrations.AlterUniqueTogether(
            name='relationexpertapplication',
            unique_together={('expert', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('name', 'vuz')},
        ),
    ]
