# Generated by Django 3.0.7 on 2020-06-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200625_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationexpertapplication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное распределение'),
        ),
    ]
