# Generated by Django 3.0.7 on 2020-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200708_1253'),
        ('app', '0003_relationexpertapplication_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('name', 'vuz')},
        ),
    ]
