# Generated by Django 3.0.7 on 2020-07-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreExpertAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.FloatField(blank=True, default=None, null=True, verbose_name='Критерий №1')),
                ('score2', models.FloatField(blank=True, default=None, null=True, verbose_name='Критерий №2')),
                ('score3', models.FloatField(blank=True, default=None, null=True, verbose_name='Критерий №3')),
                ('score4', models.FloatField(blank=True, default=None, null=True, verbose_name='Критерий №4')),
                ('score5', models.FloatField(blank=True, default=None, null=True, verbose_name='Критерий №5')),
                ('score', models.FloatField(blank=True, default=None, null=True, verbose_name='Оценка заявки')),
                ('comment_master', models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Комментарий ответственного секретаря')),
                ('check', models.BooleanField(default=False, verbose_name='Готово')),
                ('date_last', models.DateField(blank=True, default=None, null=True, verbose_name='Последнее обновление')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Все оценки ЭК по заявке',
                'verbose_name_plural': 'Все оценки ЭК по заявке',
            },
        ),
        migrations.CreateModel(
            name='ScoreExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, help_text='\n            Указание: <i> проводится экспертиза Справки о содержании контрольно-измерительных материалов направления </i>\n            <p> Данный критерий оценивает творческий характер, уровень сложности и новизну демоверсий заданий, их направленность на выявление интеллектуального потенциала, аналитических способностей и креативности мышления участников.</p>\n            <p> Данный критерий оценивает также наличие и содержание спецификаций заданий и дополнительных методических материалов.</p>', null=True, verbose_name='Критерий №1')),
                ('score2', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, help_text='\n            Указание: <i> проводится экспертиза Справки о содержании контрольно-измерительных материалов направления и Справки об организационно-методическом сопровождении направления олимпиады</i>\n            <p> Данный критерий оценивает наличие практико-ориентированной составляющей в заданиях, направленность формата проведения на выявление практических навыков и профессионального потенциала участников, а также вовлеченность партнеров-работодателей в реализацию направления</p>', null=True, verbose_name='Критерий №2')),
                ('score3', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, help_text='\n            Указание: <i>проводится экспертиза Справки об организационно-методическом сопровождении направления олимпиады </i>\n            <p> Данный критерий оценивает уровень профессиональной квалификации членов оргкомитета олимпиады, методической комиссии и жюри, а также наличие среди членов представителей партнёров-работодателей направления </p>\n        ', null=True, verbose_name='Критерий №3')),
                ('score4', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, help_text='\n            Указание: <i>проводится экспертиза Справки об образовательной организации высшего образования в контексте олимпиады </i>\n            <p> Данный критерий оценивает организационный опыт, в том числе опыт проведения Всероссийской олимпиады студентов «Я-профессионал», а также степень соответствия направления профилю образовательной организации</p>\n        ', null=True, verbose_name='Критерий №4')),
                ('score5', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, help_text='\n            Указание: <i> проводится экспертиза Общих сведений об образовательной организации высшего образования в контексте олимпиады </i>\n            <p>Данный критерий оценивает развитость и доступность инфраструктуры для предлагаемого формата организации и проведения очного этапа олимпиады соответствующего направления </p>\n        ', null=True, verbose_name='Критерий №5')),
                ('score', models.FloatField(blank=True, default=None, null=True, verbose_name='Оценка эксперта')),
                ('comment', models.TextField(blank=True, default=None, help_text='Оставьте общий комментарий по заявке (не более 1000 символов)', max_length=1000, null=True, verbose_name='Комментарий по заявке')),
                ('check', models.BooleanField(default=False, verbose_name='Готово')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('date_last', models.DateField(blank=True, default=None, null=True, verbose_name='Последнее обновление')),
                ('relation_exp_app', models.ForeignKey(default=None, limit_choices_to={'common_commission': False}, on_delete=django.db.models.deletion.CASCADE, to='app.RelationExpertApplication', verbose_name='Эксперт - заявка')),
            ],
            options={
                'verbose_name': 'Оценка эксперта ЭК по заявке',
                'verbose_name_plural': 'Оценки экспертов ЭК по заявке',
            },
        ),
        migrations.CreateModel(
            name='ScoreCommonAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=None, null=True, verbose_name='Оценка заявки')),
                ('comment_master', models.TextField(blank=True, default=None, max_length=2000, null=True, verbose_name='Комментарий ответственного секретаря')),
                ('check', models.BooleanField(default=False, verbose_name='Готово')),
                ('date_last', models.DateField(blank=True, default=None, null=True, verbose_name='Последнее обновление')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Все оценки ОК по заявке',
                'verbose_name_plural': 'Все оценки ОК по заявке',
            },
        ),
        migrations.CreateModel(
            name='ScoreCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, help_text=' Указание:  <i> проводится экспертиза Формы №5 (Сведения о возможности образовательной организации и партнеров направления по продвижению Олимпиады) и остальных документов заявки </i>\n        <p> Данный критерий оценивает: </p>\n        <ul>\n        <li>потенциал информационной активности образовательного учреждения, готовность инфраструктуры для продвижения заявленного направления и олимпиады «Я – профессионал» в целом;</li>\n        <li>авторитет вуза в заявленной сфере;</li>\n        <li>привлекательность предлагаемого направления олимпиады для участия студентов разных направлений и специальностей;</li>\n        <li>соответствие возможностей вуза проведению заявленного направления с учетом принципа географического равенства.</li>\n        </ul>', null=True, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, default=None, help_text='Оставьте общий комментарий по заявке (не более 1000 символов)', max_length=1000, null=True, verbose_name='Комментарий по заявке')),
                ('check', models.BooleanField(default=False, verbose_name='Готово')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('date_last', models.DateField(blank=True, default=None, null=True, verbose_name='Последнее обновление')),
                ('relation_exp_app', models.ForeignKey(default=None, limit_choices_to={'common_commission': True}, on_delete=django.db.models.deletion.CASCADE, to='app.RelationExpertApplication', verbose_name='Эксперт - заявка')),
            ],
            options={
                'verbose_name': 'Оценка эксперта ОК по заявке',
                'verbose_name_plural': 'Оценки экспертов ОК по заявке',
            },
        ),
        migrations.CreateModel(
            name='ScoreAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_com', models.FloatField(blank=True, default=None, null=True, verbose_name='Оценка общей комиссии')),
                ('score_exp', models.FloatField(blank=True, default=None, null=True, verbose_name='Оценка экспертной комиссии')),
                ('score_final', models.FloatField(blank=True, default=None, null=True, verbose_name='Итоговая оценка')),
                ('date_last', models.DateField(blank=True, default=None, null=True, verbose_name='Последнее обновление')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Все оценки',
                'verbose_name_plural': 'Все оценки',
            },
        ),
    ]
