# Generated by Django 3.0.7 on 2020-06-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_exp', models.BooleanField(default=False, verbose_name='Готовность Эксперта')),
                ('count_all', models.IntegerField(default=0, verbose_name='Кол-во назначенных заявок')),
                ('count_ok', models.IntegerField(default=0, verbose_name='Кол-во готовых заявок')),
                ('date_last', models.DateField(blank=True, default=None, null=True, verbose_name='Последнее обновление')),
                ('expert', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Готовность оценок по эксперта',
                'verbose_name_plural': 'Готовность оценок по эксперта',
            },
        ),
    ]
