# Generated by Django 3.0.7 on 2020-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_auto_20200626_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkexpertscore',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комметарий по эксперту'),
        ),
    ]
