# Generated by Django 3.0.7 on 2020-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_checkexpertscore_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkexpertscore',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комметарий по эксперту'),
        ),
    ]
