# Generated by Django 3.0.7 on 2020-06-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20200626_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckExpertScore',
        ),
    ]
