# Generated by Django 3.0.7 on 2020-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_auto_20200629_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecommon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
        migrations.AlterField(
            model_name='scoreexpert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
    ]
