# Generated by Django 3.0.7 on 2020-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_auto_20200629_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecommon',
            name='comment',
            field=models.TextField(blank=True, default=None, help_text='Оставьте общий комментарий по заявке (не более 1000 символов)', max_length=1000, null=True, verbose_name='Комментарий по заявке'),
        ),
        migrations.AlterField(
            model_name='scoreexpert',
            name='comment',
            field=models.TextField(blank=True, default=None, help_text='Оставьте общий комментарий по заявке (не более 1000 символов)', max_length=1000, null=True, verbose_name='Комментарий по заявке'),
        ),
    ]
