# Generated by Django 3.0.7 on 2020-06-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userexpert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'Кастомная Комиссия', 'verbose_name_plural': 'Кастомные Комиссии'},
        ),
    ]
