# Generated by Django 3.0.7 on 2020-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userexpert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_commission',
            field=models.BooleanField(default=True, verbose_name='Общая комиссия'),
        ),
    ]
