# Generated by Django 3.0.7 on 2020-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userexpert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='expert_commission',
        ),
        migrations.AddField(
            model_name='expert',
            name='comment',
            field=models.TextField(default='', verbose_name='Примичание/Комментарий'),
        ),
    ]
