# Generated by Django 3.0.7 on 2020-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userexpert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='gender',
            field=models.CharField(choices=[('m', 'Муж'), ('f', 'Жен')], default='m', max_length=2, verbose_name='Пол'),
        ),
    ]
