# Generated by Django 3.0.7 on 2020-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userexpert', '0002_auto_20200721_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примичание/Комментарий'),
        ),
    ]
