# Generated by Django 3.0.7 on 2020-07-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Федеральный округ')),
                ('short_name', models.CharField(max_length=100, verbose_name='ФО')),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Регион')),
                ('federal_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.FederalDistrict', verbose_name='Федеральный округ')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='Короткое название')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='Полное название')),
                ('is_vuz', models.BooleanField(default=True, verbose_name='Это вуз')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Вуз/Организация',
                'verbose_name_plural': 'Вузы/Организации',
                'ordering': ['full_name'],
            },
        ),
    ]
