# Generated by Django 3.0.7 on 2020-07-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Короткое название'),
        ),
    ]
