# Generated by Django 3.0.7 on 2020-07-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['full_name'], 'verbose_name': 'Вуз/Организация', 'verbose_name_plural': 'Вузы/Организации'},
        ),
        migrations.AlterModelOptions(
            name='federaldistrict',
            options={'ordering': ['full_name'], 'verbose_name': 'Федеральный округ', 'verbose_name_plural': 'Федеральные округа'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
